package craftvillage.datalayer.entities;
// Generated Mar 10, 2020 9:28:01 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import craftvillage.corelayer.utilities.ConstantParameter;

/**
 * SrCode generated by hbm2java
 */
@Entity
@Table(name = "SR_CODE", schema = ConstantParameter._SCHEMA_NAME)
public class SrCode implements java.io.Serializable {

	private int codeId;
	private String code;
	private String describe;

	public SrCode() {
	}

	public SrCode(int codeId) {
		this.codeId = codeId;
	}

	public SrCode(int codeId, String code, String describe) {
		this.codeId = codeId;
		this.code = code;
		this.describe = describe;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator="SR_CODE_SEQ")
	@Column(name = "CODE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getCodeId() {
		return this.codeId;
	}

	public void setCodeId(int codeId) {
		this.codeId = codeId;
	}

	@Column(name = "CODE", length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "DESCRIBE", length = 40)
	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

}
