package craftvillage.datalayer.entities;
// Generated Mar 10, 2020 9:28:01 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;

import craftvillage.corelayer.utilities.ConstantParameter;
import craftvillage.datalayer.entities.UserSurvey;
/**
 * SrImg generated by hbm2java
 */
@Entity
@Table(name = "SR_IMG", schema = ConstantParameter._SCHEMA_NAME)
public class SrImg implements java.io.Serializable {

	private int urImgId;
	private UserSurvey userSurvey;
	private String urImgName;
	private String urImgPath;
	private Date dateCreate;
	private Double XCoordinate;
	private Double YCoordinate;

	public SrImg() {
	}

	public SrImg(int urImgId) {
		this.urImgId = urImgId;
	}

	public SrImg(int urImgId, UserSurvey userSurvey, String urImgName, Date dateCreate, Double XCoordinate,
			Double YCoordinate, String urImgPath) {
		this.urImgId = urImgId;
		this.userSurvey = userSurvey;
		this.urImgName = urImgName;
		this.dateCreate = dateCreate;
		this.XCoordinate = XCoordinate;
		this.YCoordinate = YCoordinate;
		this.urImgPath = urImgPath;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator="SR_IMG_SEQ")
	@Column(name = "UR_IMG_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getUrImgId() {
		return this.urImgId;
	}

	public void setUrImgId(int urImgId) {
		this.urImgId = urImgId;
	}
	@JsonBackReference
	@ManyToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "SURVEY_ID")
	public UserSurvey getUserSurvey() {
		return this.userSurvey;
	}

	public void setUserSurvey(UserSurvey userSurvey) {
		this.userSurvey = userSurvey;
	}

	@Column(name = "UR_IMG_NAME", length = 100)
	public String getUrImgName() {
		return this.urImgName;
	}

	public void setUrImgName(String urImgName) {
		this.urImgName = urImgName;
	}
	@JsonFormat(pattern="dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATE", length = 7)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "X_COORDINATE", precision = 9, scale = 6)
	public Double getXCoordinate() {
		return this.XCoordinate;
	}

	public void setXCoordinate(Double XCoordinate) {
		this.XCoordinate = XCoordinate;
	}

	@Column(name = "Y_COORDINATE", precision = 9, scale = 6)
	public Double getYCoordinate() {
		return this.YCoordinate;
	}

	public void setYCoordinate(Double YCoordinate) {
		this.YCoordinate = YCoordinate;
	}

	@Column(name="UR_IMG_PATH")
	public String getUrImgPath() {
		return urImgPath;
	}

	public void setUrImgPath(String urImgPath) {
		this.urImgPath = urImgPath;
	}
	
}
