//package craftvillage.datalayer.entities;
//// Generated Mar 10, 2020 9:28:01 AM by Hibernate Tools 4.3.5.Final
//
//import java.util.HashSet;
//import java.util.Set;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.OneToMany;
//import javax.persistence.Table;
//
//import craftvillage.corelayer.utilities.ConstantParameter;
//
///**
// * SrQuestion generated by hbm2java
// */
//@Entity
//@Table(name = "SR_QUESTION", schema = ConstantParameter._SCHEMA_NAME)
//public class SrQuestion implements java.io.Serializable {
//
//	private int id;
//	private String content;
//	private String type;
//	private Set<SrAnswer> srAnswers = new HashSet<SrAnswer>(0);
//	private Set<SrSurveyQuestion> srSurveyQuestions = new HashSet<SrSurveyQuestion>(0);
//
//	public SrQuestion() {
//	}
//
//	public SrQuestion(int id) {
//		this.id = id;
//	}
//
//	public SrQuestion(int id, String content, String type, Set<SrAnswer> srAnswers,
//			Set<SrSurveyQuestion> srSurveyQuestions) {
//		this.id = id;
//		this.content = content;
//		this.type = type;
//		this.srAnswers = srAnswers;
//		this.srSurveyQuestions = srSurveyQuestions;
//	}
//
//	@Id
//	@GeneratedValue(strategy = GenerationType.AUTO, generator="SR_QUESTION_SEQ")
//	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
//	public int getId() {
//		return this.id;
//	}
//
//	public void setId(int id) {
//		this.id = id;
//	}
//
//	@Column(name = "CONTENT", length = 200)
//	public String getContent() {
//		return this.content;
//	}
//
//	public void setContent(String content) {
//		this.content = content;
//	}
//
//	@Column(name = "TYPE", length = 200)
//	public String getType() {
//		return this.type;
//	}
//
//	public void setType(String type) {
//		this.type = type;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srQuestion")
//	public Set<SrAnswer> getSrAnswers() {
//		return this.srAnswers;
//	}
//
//	public void setSrAnswers(Set<SrAnswer> srAnswers) {
//		this.srAnswers = srAnswers;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srQuestion")
//	public Set<SrSurveyQuestion> getSrSurveyQuestions() {
//		return this.srSurveyQuestions;
//	}
//
//	public void setSrSurveyQuestions(Set<SrSurveyQuestion> srSurveyQuestions) {
//		this.srSurveyQuestions = srSurveyQuestions;
//	}
//
//}
