package craftvillage.datalayer.entities;
// Generated Mar 10, 2020 9:28:01 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Where;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;

import craftvillage.corelayer.utilities.ConstantParameter;

/**
 * SrSurvey generated by hbm2java
 */
@Entity
@Table(name = "SR_SURVEY", schema = ConstantParameter._SCHEMA_NAME)
public class SrSurvey implements java.io.Serializable {

	private int id;
	private String surveyCode;
	private Date dateCreate;
	private String campainName;
	private String campainGoal;
	private int userIdCreate;
	private Set<SrActive> srActives = new LinkedHashSet<SrActive>(0);
	private Set<SrSurveyQuestion> srSurveyQuestions = new LinkedHashSet<SrSurveyQuestion>(0);

	public SrSurvey() {
	}

	public SrSurvey(int id) {
		this.id = id;
	}

	public SrSurvey(int id, Date dateCreate, String campainName, String campainGoal, int userIdCreate,
			Set<SrActive> srActives, Set<SrSurveyQuestion> srSurveyQuestions) {
		this.id = id;
		this.dateCreate = dateCreate;
		this.campainName = campainName;
		this.campainGoal = campainGoal;
		this.userIdCreate = userIdCreate;
		this.srActives = srActives;
		this.srSurveyQuestions = srSurveyQuestions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "SR_SURVEY_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "SURVEY_CODE", length = 100)
	public String getSurveyCode() {
		return surveyCode;
	}

	public void setSurveyCode(String surveyCode) {
		this.surveyCode = surveyCode;
	}
	@JsonFormat(pattern="dd/MM/yyyy")
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_CREATE", length = 7)
	public Date getDateCreate() {
		return this.dateCreate;
	}

	public void setDateCreate(Date dateCreate) {
		this.dateCreate = dateCreate;
	}

	@Column(name = "CAMPAIN_NAME", length = 200)
	public String getCampainName() {
		return this.campainName;
	}

	public void setCampainName(String campainName) {
		this.campainName = campainName;
	}

	@Column(name = "CAMPAIN_GOAL", length = 200)
	public String getCampainGoal() {
		return this.campainGoal;
	}

	public void setCampainGoal(String campainGoal) {
		this.campainGoal = campainGoal;
	}

	@Column(name = "USER_ID_CREATE", precision = 22, scale = 0)
	public int getUserIdCreate() {
		return this.userIdCreate;
	}

	public void setUserIdCreate(int userIdCreate) {
		this.userIdCreate = userIdCreate;
	}
	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srSurvey")
	public Set<SrActive> getSrActives() {
		return this.srActives;
	}

	public void setSrActives(Set<SrActive> srActives) {
		this.srActives = srActives;
	}
	@OrderBy("id ASC")
	@Where(clause ="ANSWER_ID is null")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "srSurvey")
	public Set<SrSurveyQuestion> getSrSurveyQuestions() {
		return this.srSurveyQuestions;
	}

	public void setSrSurveyQuestions(Set<SrSurveyQuestion> srSurveyQuestions) {
		this.srSurveyQuestions = srSurveyQuestions;
	}

}
