package craftvillage.datalayer.entities;
// Generated Mar 10, 2020 9:28:01 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;

import craftvillage.corelayer.utilities.ConstantParameter;

/**
 * UrSession generated by hbm2java
 */
@Entity
@Table(name = "UR_SESSION", schema = ConstantParameter._SCHEMA_NAME)
public class UrSession implements java.io.Serializable {

	private int id;
	private UrUser urUser;
	private Date loginTime;
	private String sessionString;

	public UrSession() {
	}

	public UrSession(int id) {
		this.id = id;
	}

	public UrSession(int id, UrUser urUser, Date loginTime, String sessionString) {
		this.id = id;
		this.urUser = urUser;
		this.loginTime = loginTime;
		this.sessionString = sessionString;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO, generator="UR_SESSION_SEQ")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	@JsonBackReference
	@ManyToOne( fetch = FetchType.LAZY)
	@JoinColumn(name = "UR_ID")
	public UrUser getUrUser() {
		return this.urUser;
	}

	public void setUrUser(UrUser urUser) {
		this.urUser = urUser;
	}
	@JsonFormat(pattern="dd-MM-yyyy hh:mm:ss")
	@Column(name = "LOGIN_TIME")
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Column(name = "SESSION_STRING", length = 120)
	public String getSessionString() {
		return this.sessionString;
	}

	public void setSessionString(String sessionString) {
		this.sessionString = sessionString;
	}

}
