name: fl_nynberapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # firebase_auth:
  # firebase_database:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 
  permission_handler: 
  image_picker: ^0.6.7+17
  # image_picker: ^0.8.4+2
  path_provider: 
  http:  
  shared_preferences: 
  masked_text: 
  nice_button: 
  exif: 
  
  geopoint:
  connectivity: 
  # location: 
  geolocator: '6.2.1'
  percent_indicator: ^2.1.3
  google_maps_flutter: ^0.5.33
  # google_maps_flutter: ^2.0.11
  # flutter_map: ^0.8.0
  geojson: ^0.9.1
  excel: 
  # dio: any
  # map_controller:
  #   git:
  #     url: https://github.com/ducnghia69/map_controller
  # geojson_vi: 
  #   git:
  #     url: https://github.com/ducnghia69/geojson_vi
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ic_grab.png
    - ic_email.png
    - ic_password.png
    - ic_register.png
    - ic_contact.png
    - ic_phone.png
    - img_camera.png
    - ic_username.png
    - ic_cv.png
    - ic_sdc.png
    - ic_birthday.png
    - assets/ic_power_off.png
    - assets/
    - assets/images/house.png
    - assets/images/sofa.png
    - assets/images/gadget.png
    - assets/images/bike.png
    - assets/images/pet.png
    - assets/images/car.png
    - assets/images/smartphone.png
    - assets/images/job.png
    - assets/images/powered_by.png
    - assets/images/logo.png
    - assets/images/laptop.png
    - assets/images/lenovot450.jpg
    - assets/images/samsuns9+.jpg
    - assets/images/bike.jpg
    - assets/images/sofa.jpg
    - assets/images/canon.jpg
    - assets/images/sofa.png
    - assets/images/dress.png
    - assets/images/menubutton.png
    - assets/images/navi.jpg
    - assets/images/avatar.png
    - assets/images/icon_screen/archievements.png
    - assets/images/icon_screen/cvmap.png
    - assets/images/icon_screen/image_library.png
    - assets/images/icon_screen/logs.png
    - assets/images/icon_screen/manager.png
    - assets/images/icon_screen/news.png
    - assets/images/icon_screen/surveys_completed.png
    - assets/images/icon_screen/surveys_progress.png
    - assets/images/icon_screen/talk.png
    - assets/images/icon_screen/new_survey.png
    - assets/json/ipconfig.json
    - assets/excel/language_excel.xlsx
    - assets/excel/CVlang.xlsx
    - assets/map/vietnam_regions.geojson
    - assets/map/vietnam_provinces.json
    - assets/map/vietnam_districts.json
    - assets/map/map_style.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
